version: "3.7"

services:

  # Accessible at http://localhost:3001
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.dev.front
    ports:
      - "3001:8000"
    depends_on:
      - cms
      - backend
    environment:
      # Provide only if the backend URI is different to the frontend URI
      - BACKEND_URI=http://localhost:3000
      - CMS_URI=http://localhost:27017
    volumes:
      - ./src/front:/front
      - /front/node_modules  # mount node modules from built container

  # Accessible at http://localhost:3000
  backend:
    build:
      context: .
      dockerfile: Dockerfile.dev.back
    env_file:
      - .env
    ports:
      - "3000:3000"
    depends_on:
      - cms
      - db

  # Accessible at http://localhost:1337
  cms:
    image: strapi/strapi
    restart: unless-stopped
    env_file: .env
    environment:
      DATABASE_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      DATABASE_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - ./STRAPI_APP_CONTENT:/srv/app
    depends_on:
      - db
    ports:
      - "1337:1337"

  # Accessible at mongodb://username:password@localhost:27017
  db:
    image: mongo
    restart: unless-stopped
    env_file: .env
    volumes:
      - db-data-dev:/data/db
    ports:
      - "27017:27017"

volumes:
  # Database persistence
  db-data-dev:
