version: "3.7"

services:

  # Website
  web:
    build:
      context: .
      dockerfile: Dockerfile.prod
    restart: unless-stopped
    env_file: .env
    networks:
     - web
     - backend
    depends_on:
     - db
     - cms
    labels:
     - "traefik.enable=true"
     - "traefik.http.routers.arapiles-web.rule=Host(`uqmc.org`) || Host(`www.uqmc.org`)"
     - "traefik.http.routers.arapiles-web.entrypoints=web"
     - "traefik.http.routers.arapiles-web.middlewares=redirect@file"
     - "traefik.http.routers.arapiles-secured.rule=Host(`uqmc.org`) || Host(`www.uqmc.org`)"
     - "traefik.http.routers.arapiles-secured.entrypoints=web-secured"
     - "traefik.http.routers.arapiles-secured.tls.certresolver=mytlschallenge"
     - "traefik.http.services.arapiles.loadbalancer.server.port=3000"

  # Since Traefik, as an edge-router, does not god-damn work with Strapi for
  #  some entirely unknown reason we're gonna just use nginx as a proxy for
  #  Strapi's static file service. If someone could, one day, figure out why
  #  Traefik didn't fucking work in the first place after the love and devotion
  #  shown to trying to debug this mess, that would be swell, hey?
  #
  # The nginx.conf given in the repo will serve http://cms:1337/ to all entry-
  #  points as the default server. This is because Traefik will only redirect
  #  traffic from cms.uqmc.org to Nginx in the first place.
  nginx:
    image: nginx
    volumes:
     - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
     - web
     - backend
    depends_on:
      - cms
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.homesite-web.rule=Host(`cms.uqmc.org`)"
      - "traefik.http.routers.homesite-web.entrypoints=web"
      - "traefik.http.routers.homesite-web.middlewares=redirect@file"
      - "traefik.http.routers.homesite-secured.rule=Host(`cms.uqmc.org`)"
      - "traefik.http.routers.homesite-secured.entrypoints=web-secured"
      - "traefik.http.routers.homesite-secured.tls.certresolver=mytlschallenge"
      - "traefik.http.services.homesite.loadbalancer.server.port=80"

  # Content management system
  cms:
    image: strapi/strapi
    restart: unless-stopped
    env_file: .env
    environment:
      DATABASE_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      DATABASE_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - ./STRAPI_APP_CONTENT:/srv/app
    depends_on:
      - db
    networks:
     - backend

  # Database
  db:
    image: mongo
    restart: unless-stopped
    env_file: .env
    networks:
      - backend
    volumes:
      - db-data:/data/db

  # TODO: Add Docker Volume Backup

volumes:
  # Database persistance
  db-data:

networks:
  web:
    external: true
  backend:
    external: false
