version: "3.7"

services:

  # Website
  web:
    build:
      context: .
      dockerfile: Dockerfile.prod
    restart: unless-stopped
    env_file: .env
    ports:
     - "3000:3000"
    depends_on:
     - db

  # Database
  db:
    image: postgres
    env_file: .env
    volumes:
     - db-data:/var/lib/postgresql/data

  # TODO: Add Docker Volume Backup

volumes:
  # Database persistance
  db-data:
