version: "3.7"

services:

  # Accessible at http://localhost:3000
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:8000"
    depends_on:
      - cms
    volumes:
      - ./src/front:/front
      - /front/node_modules  # Mount node modules from built container

  # Accessible at http://localhost:1337
  cms:
    image: strapi/strapi
    restart: unless-stopped
    env_file: .env
    environment:
      DATABASE_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      DATABASE_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - ./STRAPI_APP_CONTENT:/srv/app
    depends_on:
      - db
    ports:
      - "1337:1337"

  # Accessible at mongodb://username:password@localhost:27017
  db:
    image: mongo
    restart: unless-stopped
    env_file: .env
    volumes:
      - db-data-dev:/data/db
    ports:
      - "27017:27017"

volumes:
  # Database persistence
  db-data-dev:
