version: "3.7"

services:

  # Website
  web:
    build:
      context: .
      dockerfile: Dockerfile.prod
    restart: unless-stopped
    env_file: .env
    networks:
     - web
     - backend
    depends_on:
     - db
    labels:
     - "traefik.enable=true"
     - "traefik.http.routers.homesite-web.rule=Host(`uqmc.org`) || Host(`www.uqmc.org`)"
     - "traefik.http.routers.homesite-web.entrypoints=web"
     - "traefik.http.routers.homesite-web.middlewares=redirect@file"
     - "traefik.http.routers.homesite-secured.rule=Host(`uqmc.org`) || Host(`www.uqmc.org`)"
     - "traefik.http.routers.homesite-secured.entrypoints=web-secured"
     - "traefik.http.routers.homesite-secured.tls.certresolver=mytlschallenge"
     - "traefik.http.services.homesite.loadbalancer.server.port=3000"

  # Database
  db:
    image: postgres
    env_file: .env
    networks:
     - backend
    volumes:
     - db-data:/var/lib/postgresql/data

  # TODO: Add Docker Volume Backup

volumes:
  # Database persistance
  db-data:

networks:
  web:
    external: true
  backend:
    external: false
